services:
  minio:
    image: minio/minio
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: server /minio-data/data

#  podman run -p 9000:9000 -p 9001:9001 minio/minio server /data --console-address ":9001"